# Generated by Django 2.2.3 on 2019-07-23 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('tracks', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('duration', models.DateTimeField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runapp.Album')),
            ],
        ),
    ]
