# Generated by Django 2.2.3 on 2019-07-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runapp', '0002_album_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='tracks',
            field=models.CharField(max_length=200),
        ),
    ]
