# Generated by Django 2.2.3 on 2019-07-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runapp', '0003_auto_20190723_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
